import { FormEvent, ReactNode, useEffect, useRef, useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import QRCode from 'qrcode';
import jsQR from 'jsqr';
import { api, checkinSession, idempotencyKey } from './api';
import './checkin.css';
import './camera.css';

type EventItem = { id: string; title: string; slug: string; venue: string; starts_at: string; ends_at: string; status: string; capacity: number; sold_count: number };
type RegistrationField={id:string;key:string;label:string;type:'text'|'mobile'|'email'|'number'|'select'|'textarea';required:boolean;enabled:boolean;placeholder?:string;options?:string[]};
type PublicEvent = EventItem & { description: string; hero_color: string; form_background_color: string; preview?:boolean; registration_form:RegistrationField[]; ticketTypes: Array<{ id: string; name: string; price_cents: number; capacity: number; sold_count: number }> };

function Shell({ children }: { children: ReactNode }) {
  return <div className="app-shell">
    <aside>
      <Link to="/" className="brand"><span className="brand-mark">EV</span><span>EventVivid<small>活动运营 SaaS</small></span></Link>
      <nav>
        <a href="http://localhost:5174">总部后台</a><NavLink to="/organizer">活动管理</NavLink>
        <NavLink to="/e/demo-event">参会人报名</NavLink><NavLink to="/checkin">现场验签</NavLink>
      </nav>
      <div className="tenant"><span className="status-dot" />EventVivid 示例企业<small>开发环境</small></div>
    </aside>
    <main>{children}</main>
  </div>;
}

function Home() {
  return <Shell><header><p className="eyebrow">EVENT OPERATIONS, REIMAGINED</p><h1>每一场相聚，<br/><em>都鲜活发生。</em></h1><p className="lede">从发布、报名和收款，到出票与现场验签，EventVivid 让活动团队在一套系统里完成全流程运营。</p></header>
    <section className="portal-grid">
      {[
        {to:'/hq',title:'总部后台',desc:'管理租户、电子票额度、渠道和平台健康度',no:'01'}, {to:'/organizer',title:'活动管理平台',desc:'创建活动、配置票种、查看报名与交易',no:'02'},
        {to:'/e/demo-event',title:'参会人报名页',desc:'移动优先的报名、支付与电子票体验',no:'03'}, {to:'/checkin',title:'工作人员验签',desc:'快速核验、重复拦截与现场统计',no:'04'},
      ].map(({to,title,desc,no}) => <Link className="portal-card" to={to} key={to}><b>{no}</b><h2>{title}</h2><p>{desc}</p><span>进入 →</span></Link>)}
    </section>
  </Shell>;
}

function HqRedirect() { useEffect(() => { window.location.replace('http://localhost:5174'); }, []); return <Empty text="正在进入独立的总部运营中心…"/>; }

function Organizer() {
  const [events, setEvents] = useState<EventItem[]>([]); const [message, setMessage] = useState('');
  const load = () => api<EventItem[]>('/events').then(setEvents).catch((e: Error) => setMessage(e.message));
  useEffect(() => { void load(); }, []);
  async function create(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const formElement = e.currentTarget; const form = new FormData(formElement); setMessage('');
    try {
      const event = await api<EventItem>('/events', { method: 'POST', body: JSON.stringify({ title: form.get('title'), slug: form.get('slug'), venue: form.get('venue'), description: form.get('description'), startsAt: form.get('startsAt'), endsAt: form.get('endsAt') }) });
      await api(`/events/${event.id}/ticket-types`, { method: 'POST', body: JSON.stringify({ name: '标准票', priceCents: Number(form.get('price')) * 100, capacity: Number(form.get('capacity')), saleStartsAt: new Date().toISOString(), saleEndsAt: form.get('startsAt') }) });
      setMessage('活动与标准票已创建，可在列表中发布。'); formElement.reset(); load();
    } catch (error) { setMessage((error as Error).message); }
  }
  async function publish(id: string) { try { await api(`/events/${id}/publish`, { method: 'POST' }); setMessage('活动已发布。'); load(); } catch (e) { setMessage((e as Error).message); } }
  return <Shell><PageTitle kicker="ORGANIZER WORKSPACE" title="活动管理平台" subtitle="创建活动、配置票种并发布报名页面" />
    {message && <div className="notice">{message}</div>}
    <div className="two-col"><section className="panel"><div className="panel-title"><div><span>快速创建</span><h2>新活动</h2></div></div><form onSubmit={create} className="form-grid">
      <label>活动名称<input name="title" required placeholder="2026 产品创新大会"/></label><label>短链接<input name="slug" required pattern="[a-z0-9-]{3,60}" placeholder="product-day-2026"/></label>
      <label className="span-2">活动地点<input name="venue" required placeholder="上海 · 西岸艺术中心"/></label><label>开始时间<input name="startsAt" type="datetime-local" required/></label><label>结束时间<input name="endsAt" type="datetime-local" required/></label>
      <label>标准票价格（元）<input name="price" type="number" min="0" defaultValue="0" required/></label><label>库存<input name="capacity" type="number" min="1" defaultValue="100" required/></label>
      <label className="span-2">活动简介<textarea name="description" rows={3} placeholder="用一句话描述活动亮点"/></label><button className="primary span-2">创建活动与票种</button>
    </form></section>
    <section className="panel"><div className="panel-title"><div><span>活动资产</span><h2>最近活动</h2></div><b>{events.length}</b></div><div className="event-list">{events.length === 0 ? <Empty text="还没有活动，先创建第一场吧。"/> : events.map(event => <article key={event.id}><div><span className={`pill ${event.status === 'published' ? 'success' : ''}`}>{event.status}</span><h3>{event.title}</h3><p>{event.venue} · {new Date(event.starts_at).toLocaleString()}</p><small>售出 {event.sold_count}/{event.capacity}</small></div><div className="actions">{event.status === 'draft' && <button onClick={() => publish(event.id)}>发布</button>}<Link to={`/e/${event.slug}`}>报名页</Link></div></article>)}</div></section></div>
  </Shell>;
}

function Attendee() {
  const { slug = '' } = useParams();const navigate=useNavigate();const[searchParams]=useSearchParams();const previewToken=searchParams.get('preview')??''; const [event, setEvent] = useState<PublicEvent>(); const [error, setError] = useState(''); const [result, setResult] = useState<{ orderId: string; orderNo: string; amountCents: number; ticket?: { code: string } }>();
  useEffect(() => { const path=previewToken?`/public/events/${slug}/preview?token=${encodeURIComponent(previewToken)}`:`/public/events/${slug}`;api<PublicEvent>(path).then(setEvent).catch((e: Error) => setError(e.message)); }, [slug,previewToken]);
  useEffect(()=>{if(!event)return;const timeNode=document.querySelector<HTMLElement>('.event-hero > div > b');const format=(value:string)=>new Date(value).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});if(timeNode)timeNode.textContent=`${format(event.starts_at)} — ${format(event.ends_at)}`},[event]);
  useEffect(()=>{if(!event)return;const labels=Array.from(document.querySelectorAll<HTMLElement>('.registration-card label'));const fields=(event.registration_form??[]).filter(field=>field.enabled);labels.slice(1).forEach((label,index)=>{label.querySelector(':scope > .required-star')?.remove();const title=label.querySelector('span');if(fields[index]?.required&&title&&!title.querySelector('.required-star')){const star=document.createElement('em');star.className='required-star';star.textContent=' *';title.append(star)}})},[event]);
  useEffect(()=>{document.querySelector<HTMLElement>('.registration-card h2')?.replaceChildren('填写报名信息')},[event]);
  useEffect(()=>{if(!result?.ticket?.code)return;navigate(`/ticket/${result.ticket.code}`,{replace:true})},[navigate,result]);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!event||event.preview) return; const form = new FormData(e.currentTarget); const fields=(event.registration_form??[]).filter(field=>field.enabled);const formData=Object.fromEntries(fields.map(field=>[field.key,String(form.get(`field_${field.key}`)??'')]));const mobile=String(formData.mobile??'').trim();if(mobile)localStorage.setItem('eventvivid_ticket_mobile',mobile);setError(''); try { const order = await api<{orderId:string;orderNo:string;amountCents:number}>(`/public/events/${slug}/registrations`, { method:'POST', headers:{'idempotency-key':idempotencyKey()}, body:JSON.stringify({ticketTypeId:form.get('ticketTypeId'),attendeeName:formData.name,attendeeMobile:formData.mobile,attendeeEmail:formData.email??'',formData}) }); const paid = await api<{ticket:{code:string}}>(`/orders/${order.orderId}/payments/confirm`, {method:'POST',headers:{'idempotency-key':idempotencyKey()}}); setResult({...order,ticket:paid.ticket}); } catch (e) { setError((e as Error).message); } }
  if (error && !event) return <MobileFrame><Empty text={error}/></MobileFrame>;
  if (!event) return <MobileFrame><Empty text="正在加载活动…"/></MobileFrame>;
  if (result?.ticket) return <MobileFrame ticketLookup={false}><div className="ticket-success"><span>✓</span><p>报名成功</p><h1>{event.title}</h1><div className="ticket-code"><small>电子票码</small><b>{result.ticket.code}</b></div><p>请妥善保存，入场时向工作人员出示。可凭手机号随时查询电子票。</p><Link to={`/ticket/${result.ticket.code}`} className="primary button-link">查看电子票</Link><Link to={`/e/${slug}/tickets`} className="ticket-lookup-link">查询我的票券</Link></div></MobileFrame>;
  return <MobileFrame>{event.preview&&<div className="preview-banner"><b>预览模式</b><span>此页面仅用于检查展示效果，不会提交报名。</span></div>}<div className="event-hero" style={{background:event.hero_color}}><p className="eyebrow">EVENTVIVID PRESENTS</p><h1>{event.title}</h1><p>{event.description}</p><div><b>{new Date(event.starts_at).toLocaleString()}</b><span>{event.venue}</span></div></div><form className="registration-card" style={{background:event.form_background_color}} onSubmit={submit}><h2>立即报名</h2><label>选择票种<select name="ticketTypeId">{event.ticketTypes.map(t => <option value={t.id} key={t.id}>{t.name} · {t.price_cents === 0 ? '免费' : `¥${t.price_cents/100}`} · 剩余 {t.capacity-t.sold_count}</option>)}</select></label>{(event.registration_form??[]).filter(field=>field.enabled).map(field=><label key={field.id}><span>{field.label}{!field.required&&<small>（选填）</small>}</span>{field.type==='textarea'?<textarea name={`field_${field.key}`} required={field.required} rows={3} placeholder={field.placeholder}/>:field.type==='select'?<select name={`field_${field.key}`} required={field.required}><option value="">{field.placeholder||'请选择'}</option>{field.options?.map(option=><option value={option} key={option}>{option}</option>)}</select>:<input name={`field_${field.key}`} required={field.required} type={field.type==='email'?'email':field.type==='number'?'number':field.type==='mobile'?'tel':'text'} min={field.type==='number'?0:undefined} pattern={field.type==='mobile'?'1\\d{10}':undefined} placeholder={field.placeholder}/>}</label>)}{error && <div className="notice error">{error}</div>}<button className="primary" disabled={event.preview}>{event.preview?'预览模式不可提交':'确认报名'}</button><small>{event.preview?'关闭预览后返回活动平台继续配置。':'提交即表示同意活动报名服务协议和隐私政策。'}</small></form></MobileFrame>;
}

const ticketStatusLabels:Record<string,string>={valid:'有效，可入场',checked_in:'已验签入场',void:'已作废',refunded:'已退款'};
type TicketLookupItem={code:string;status:string;attendee_name:string;ticket_type_name:string;created_at:string};
type CheckinEvent={id:string;title:string;venue:string;starts_at:string;ends_at:string};
type CheckinPointOption={id:string;name:string};
type BarcodeDetectorInstance={detect:(source:ImageBitmapSource)=>Promise<Array<{rawValue:string}>>};
type BarcodeDetectorConstructor=new(options:{formats:string[]})=>BarcodeDetectorInstance;
function TicketLookup(){const{slug=''}=useParams();const[mobile,setMobile]=useState('');const[tickets,setTickets]=useState<TicketLookupItem[]>([]);const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[searched,setSearched]=useState(false);async function lookup(lookupMobile:string){setLoading(true);setSearched(true);setError('');try{setTickets(await api<TicketLookupItem[]>(`/public/events/${slug}/tickets?mobile=${encodeURIComponent(lookupMobile)}`))}catch(e){setTickets([]);setError((e as Error).message)}finally{setLoading(false)}}useEffect(()=>{const cachedMobile=(localStorage.getItem('eventvivid_ticket_mobile')??'').trim();if(!cachedMobile)return;setMobile(cachedMobile);void lookup(cachedMobile)},[slug]);async function search(e:FormEvent<HTMLFormElement>){e.preventDefault();const lookupMobile=mobile.trim();if(lookupMobile)localStorage.setItem('eventvivid_ticket_mobile',lookupMobile);await lookup(lookupMobile)}return <MobileFrame><div className="ticket-lookup"><Link to={`/e/${slug}`} className="back-link">← 返回报名页</Link><p className="eyebrow">MY TICKETS</p><h1>查询我的票券</h1><p>输入报名时使用的手机号，查看本活动下的全部电子票。</p><form onSubmit={search}><label>报名手机号<input value={mobile} onChange={e=>{setMobile(e.target.value);setSearched(false);setError('')}} inputMode="numeric" pattern="1\d{10}" maxLength={11} required placeholder="请输入 11 位手机号"/></label><button className="primary" disabled={loading}>{loading?'查询中…':'查询电子票'}</button></form>{error&&<div className="notice error">{error}</div>}{tickets.length>0&&<div className="ticket-lookup-list">{tickets.map(ticket=><Link key={ticket.code} to={`/ticket/${ticket.code}`}><div><b>{ticket.ticket_type_name}</b><small>{ticket.attendee_name} · {ticket.code}</small></div><span>{ticketStatusLabels[ticket.status]??ticket.status} →</span></Link>)}</div>}{searched&&!loading&&!error&&tickets.length===0&&<p className="lookup-empty">未找到该手机号的电子票。</p>}</div></MobileFrame>}
function TicketQr({code}:{code:string}){const canvasRef=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(canvasRef.current)void QRCode.toCanvas(canvasRef.current,code,{width:250,margin:1,errorCorrectionLevel:'M',color:{dark:'#101828',light:'#ffffff'}})},[code]);return <div className="ticket-qr"><canvas ref={canvasRef} aria-label="电子票二维码"/></div>}
function TicketPage() { const { code='' } = useParams(); const [ticket,setTicket]=useState<Record<string,string>>(); const [error,setError]=useState(''); useEffect(()=>{api<Record<string,string>>(`/public/tickets/${code}`).then(setTicket).catch((e:Error)=>setError(e.message));},[code]); return <MobileFrame>{ticket ? <div className="digital-ticket"><p className="eyebrow">ADMISSION TICKET</p><h1>{ticket.title}</h1><TicketQr code={ticket.code??code}/><b>{ticket.code}</b><p className="ticket-save-tip">请妥善保存，入场时向工作人员出示。</p><dl><div><dt>参会人</dt><dd>{ticket.attendee_name}</dd></div><div><dt>票种</dt><dd>{ticket.ticket_type_name}</dd></div><div><dt>地点</dt><dd>{ticket.venue}</dd></div><div><dt>状态</dt><dd>{ticketStatusLabels[ticket.status??'']??ticket.status}</dd></div></dl><Link className="ticket-lookup-link" to={`/e/${ticket.slug}/tickets`}>查看我的票券</Link></div> : <Empty text={error||'正在获取电子票…'}/>}</MobileFrame>; }

function Checkin() {
  const [code,setCode]=useState(''); const [eventId,setEventId]=useState(''); const [pointId,setPointId]=useState(''); const [result,setResult]=useState<{message:string;result:string}>(); const [message,setMessage]=useState('');const[loggedIn,setLoggedIn]=useState(Boolean(checkinSession.get()));const[loggingIn,setLoggingIn]=useState(false);const[events,setEvents]=useState<CheckinEvent[]>([]);const[points,setPoints]=useState<CheckinPointOption[]>([]);const[loadingEvents,setLoadingEvents]=useState(false);const[cameraOpen,setCameraOpen]=useState(false);const[cameraError,setCameraError]=useState('');const videoRef=useRef<HTMLVideoElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const streamRef=useRef<MediaStream>();const scanTimerRef=useRef<number>();
  function stopCamera(){if(scanTimerRef.current)window.clearInterval(scanTimerRef.current);scanTimerRef.current=undefined;streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=undefined;if(videoRef.current)videoRef.current.srcObject=null;setCameraOpen(false)}
  function logout(){stopCamera();checkinSession.clear();setLoggedIn(false);setCode('');setEventId('');setPointId('');setEvents([]);setPoints([]);setResult(undefined);setMessage('');}
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setLoggingIn(true);setMessage('');try{const result=await api<{token:string}>('/auth/login',{method:'POST',body:JSON.stringify({username:form.get('mobile'),password:form.get('password')})});checkinSession.set(result.token);setLoggedIn(true);setMessage('登录成功，请加载活动验签点。')}catch(e){setMessage((e as Error).message)}finally{setLoggingIn(false)}}
  async function loadEvents(){setLoadingEvents(true);setMessage('');try{const items=await api<CheckinEvent[]>('/checkins/my-events');setEvents(items);if(items[0]){setEventId(items[0].id);await loadPoints(items[0].id)}else{setEventId('');setPointId('');setPoints([]);setMessage('当前没有进行中的已授权活动。')}}catch(e){setEvents([]);setPoints([]);setMessage((e as Error).message)}finally{setLoadingEvents(false)}}
  useEffect(()=>{if(loggedIn)void loadEvents()},[loggedIn]);
  async function loadPoints(selectedEventId:string) { if(!selectedEventId){setPointId('');setPoints([]);return}try { const items=await api<CheckinPointOption[]>(`/checkins/points/${encodeURIComponent(selectedEventId)}`);setPoints(items);if(items[0]){setPointId(items[0].id);setMessage('');} else {setPointId('');setMessage('该活动没有可使用的验签点，或您尚未获得验签点授权。');} } catch(e){setPointId('');setPoints([]);setMessage((e as Error).message);} }
  async function verifyTicket(ticketCode:string){try{setResult(await api('/checkins/scan',{method:'POST',headers:{'idempotency-key':idempotencyKey()},body:JSON.stringify({code:ticketCode,checkinPointId:pointId})}));}catch(e){setResult({result:'invalid',message:(e as Error).message});}}
  async function scan(e:FormEvent){e.preventDefault();if(!code.trim()){void startCamera();return}await verifyTicket(code.trim())}
  async function startCamera(){if(!pointId){setCameraError('请先选择活动和验签点。');return}const Detector=(window as Window & {BarcodeDetector?:BarcodeDetectorConstructor}).BarcodeDetector;setCameraError('');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});streamRef.current=stream;setCameraOpen(true);requestAnimationFrame(()=>{const video=videoRef.current;if(!video)return;video.srcObject=stream;void video.play();const detector=Detector?new Detector({formats:['qr_code']}):undefined;let recognized=false;scanTimerRef.current=window.setInterval(()=>{if(recognized||video.readyState<2||!video.videoWidth)return;const handleCode=(rawValue?:string)=>{const ticketCode=rawValue?.trim();if(!ticketCode)return;recognized=true;setCode(ticketCode);stopCamera();void verifyTicket(ticketCode)};if(detector){void detector.detect(video).then(codes=>handleCode(codes[0]?.rawValue)).catch(()=>undefined);return}const canvas=canvasRef.current;const context=canvas?.getContext('2d',{willReadFrequently:true});if(!canvas||!context)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;context.drawImage(video,0,0,canvas.width,canvas.height);const image=context.getImageData(0,0,canvas.width,canvas.height);handleCode(jsQR(image.data,canvas.width,canvas.height,{inversionAttempts:'dontInvert'})?.data)},300)})}catch(e){setCameraError((e as Error).name==='NotAllowedError'?'未获得摄像头权限，请允许浏览器使用摄像头后重试。':'无法打开摄像头，请检查设备或浏览器权限。')}}
  useEffect(()=>()=>stopCamera(),[]);
  if(!loggedIn)return <MobileFrame ticketLookup={false}><div className="checkin-mobile"><header className="checkin-mobile-hero"><p className="eyebrow">VENUE OPERATIONS</p><h1>工作人员登录</h1><p>请使用已获得验签授权的活动平台账号登录。</p></header><section className="checkin-mobile-card"><form className="checkin-login-form" onSubmit={login}><label>手机号<input name="mobile" type="tel" required pattern="1[3-9][0-9]{9}" placeholder="请输入登录手机号"/></label><label>密码<input name="password" type="password" required minLength={8} placeholder="请输入密码"/></label>{message&&<p className="muted">{message}</p>}<button className="primary" disabled={loggingIn}>{loggingIn?'登录中…':'登录并开始验签'}</button></form></section></div></MobileFrame>;
  return <MobileFrame ticketLookup={false}><div className="checkin-mobile"><header className="checkin-mobile-hero"><div className="checkin-mobile-top"><span>现场验签</span><button type="button" onClick={logout}>退出</button></div><p className="eyebrow">VENUE OPERATIONS</p><h1>验签工作台</h1><p>选择活动和验签点后，核验参会人的电子票。</p></header><section className="checkin-mobile-card"><div className="checkin-mobile-form"><label>进行中的活动<select value={eventId} onChange={e=>{const id=e.target.value;setEventId(id);setPointId('');setResult(undefined);void loadPoints(id)}} disabled={loadingEvents}><option value="">{loadingEvents?'正在加载活动…':'请选择活动'}</option>{events.map(item=><option value={item.id} key={item.id}>{item.title} · {item.venue}</option>)}</select></label><label>验签点<select value={pointId} onChange={e=>{setPointId(e.target.value);setResult(undefined)}} disabled={!points.length}><option value="">请选择验签点</option>{points.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><button type="button" className="refresh-checkin" onClick={()=>void loadEvents()} disabled={loadingEvents}>{loadingEvents?'刷新中…':'刷新活动'}</button></div>{message&&<p className="checkin-message">{message}</p>}{cameraError&&<p className="camera-error">{cameraError}</p>}{cameraOpen&&<div className="camera-preview"><video ref={videoRef} playsInline muted/><canvas ref={canvasRef} className="qr-decode-canvas"/><button type="button" onClick={stopCamera}>取消扫码</button></div>}<form className="checkin-code-form" onSubmit={scan}><label>电子票码<input value={code} onChange={e=>setCode(e.target.value)} placeholder="扫描后自动填入，也可手动输入"/></label><button className="primary" type="button" onClick={()=>void startCamera()} disabled={!pointId}>核验票券</button><button className="manual-checkin" type="submit" disabled={!pointId||!code.trim()}>手动核验票码</button></form>{result&&<div className={`result ${result.result}`}><b>{result.result==='success'?'✓':'!'}</b><h3>{result.message}</h3><p>{code}</p></div>}<div className="tips"><b>操作提示</b><p>点击“核验票券”后允许使用摄像头；识别二维码后会自动完成验签。</p></div></section></div></MobileFrame>;
}

function PageTitle({kicker,title,subtitle}:{kicker:string;title:string;subtitle:string}){return <div className="page-title"><div><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{subtitle}</p></div><div className="avatar">管</div></div>}
function Metric({value,label,trend}:{value:string;label:string;trend:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{trend}</small></article>}
function Empty({text}:{text:string}){return <div className="empty"><span>EV</span><p>{text}</p></div>}
function MobileFrame({children,ticketLookup=true}:{children:ReactNode;ticketLookup?:boolean}){const{pathname}=useLocation();const match=pathname.match(/^\/e\/([^/]+)$/);return <div className="mobile-bg"><Link to="/" className="mobile-brand">EventVivid</Link><div className="mobile-frame">{children}{ticketLookup&&match&&<Link className="ticket-lookup-entry" to={`/e/${match[1]}/tickets`}>查询我的票券</Link>}</div></div>}

export function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/hq" element={<HqRedirect/>}/><Route path="/organizer" element={<Organizer/>}/><Route path="/e/:slug" element={<Attendee/>}/><Route path="/e/:slug/tickets" element={<TicketLookup/>}/><Route path="/ticket/:code" element={<TicketPage/>}/><Route path="/checkin" element={<Checkin/>}/></Routes>}
