import { FormEvent, ReactNode, useEffect, useRef, useState } from 'react';
import { Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { api, session } from './api';

type User = { id:string; username:string; displayName:string; role:string };
type DashboardData = { tenants:number; events:number; orders:number; paidAmountCents:number; checkedIn:number };
type Tenant = { id:string; name:string; status:'active'|'suspended'; valid_until:string|null; created_at:string; event_count:number; credit_balance:number|null; credit_reserved:number|null };
type TenantAdmin = { id:string; name:string; mobile:string|null; username:string|null; status:'active'|'disabled'; last_login_at:string|null; created_at:string };
type CreditEntry = { id:string; change:number; kind:string; reference:string; note:string; created_at:string };
type CreditWallet = { balance:number; reserved:number; available:number; entries:CreditEntry[] };
type Audit = { id:string; action:string; target_type:string; target_id:string|null; detail:unknown; ip_address:string|null; created_at:string; display_name:string };

function Login({ onLogin }:{onLogin:(user:User)=>void}) {
  const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const form=new FormData(e.currentTarget);try{const result=await api<{token:string;user:User}>('/hq/auth/login',{method:'POST',body:JSON.stringify({username:form.get('username'),password:form.get('password')})});session.set(result.token);onLogin(result.user);}catch(e){setError((e as Error).message);}finally{setLoading(false)}}
  return <div className="login-page"><section className="login-story"><div className="logo light"><b>EV</b><span>EventVivid<small>HEADQUARTERS</small></span></div><div><p className="eyebrow">PLATFORM OPERATIONS</p><h1>让每一场活动，<br/>被稳定地托住。</h1><p>总部运营中心用于管理租户、电子票额度、支付渠道、平台风险与审计记录。</p></div><footer>EventVivid Platform · Internal Use Only</footer></section><section className="login-panel"><form onSubmit={submit}><div className="logo dark"><b>EV</b><span>总部运营中心<small>安全登录</small></span></div><h2>欢迎回来</h2><p>请输入总部管理员账户继续</p><label>管理员账号<input name="username" autoComplete="username" required autoFocus placeholder="admin"/></label><label>登录密码<input name="password" type="password" autoComplete="current-password" required placeholder="••••••••••••"/></label>{error&&<div className="alert">{error}</div>}<button className="primary" disabled={loading}>{loading?'正在验证…':'登录总部后台'}</button><small>登录行为将写入平台审计日志</small></form></section></div>;
}

function Layout({user,onLogout,children}:{user:User;onLogout:()=>void;children:ReactNode}){
  const nav=[{to:'/',label:'总览',icon:'⌂'},{to:'/tenants',label:'租户管理',icon:'▦'},{to:'/credits',label:'电子票额度',icon:'◇'},{to:'/channels',label:'支付渠道',icon:'↗'},{to:'/risk',label:'风控中心',icon:'△'},{to:'/audit',label:'审计日志',icon:'≡'},{to:'/settings',label:'平台设置',icon:'⚙'}];
  return <div className="shell"><aside><div className="logo light"><b>EV</b><span>EventVivid<small>HEADQUARTERS</small></span></div><nav>{nav.map(({to,label,icon})=><NavLink to={to} end={to==='/'} key={to}><i>{icon}</i>{label}</NavLink>)}</nav><div className="operator"><div className="avatar">{user.displayName[0]}</div><div><b>{user.displayName}</b><small>{user.role}</small></div><button onClick={onLogout}>退出</button></div></aside><main>{children}</main></div>;
}

function PageHeader({title,subtitle,action}:{title:string;subtitle:string;action?:ReactNode}){return <header className="page-header"><div><p className="eyebrow">EVENTVIVID HQ</p><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>}
function Loading(){return <div className="loading">正在加载总部数据…</div>}

function Dashboard(){const [data,setData]=useState<DashboardData>();useEffect(()=>{void api<DashboardData>('/hq/dashboard').then(setData)},[]);if(!data)return <Loading/>;return <><PageHeader title="平台总览" subtitle="跨租户业务运行、交易与服务健康度"/><section className="metrics"><Metric label="平台租户" value={String(data.tenants)} note="全部客户空间"/><Metric label="累计活动" value={String(data.events)} note="跨租户活动总量"/><Metric label="平台订单" value={String(data.orders)} note="报名交易订单"/><Metric label="已支付金额" value={`¥ ${(data.paidAmountCents/100).toLocaleString()}`} note="当前累计口径"/></section><div className="dashboard-grid"><section className="card hero-card"><div><p className="eyebrow">SERVICE PULSE</p><h2>平台运行平稳</h2><p>核心 API 与远程 PostgreSQL 已连接，租户数据按边界隔离。</p></div><div className="pulse"><span/><b>99.99%</b><small>目标可用性</small></div></section><section className="card"><div className="card-head"><h2>现场活跃度</h2><span className="badge green">实时</span></div><div className="big-number">{data.checkedIn}</div><p className="muted">累计完成验签人次</p><div className="bar"><i style={{width:`${Math.min(data.checkedIn*10,100)}%`}}/></div></section></div></>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}

function Tenants(){
  const [items,setItems]=useState<Tenant[]>([]);const [message,setMessage]=useState('');const [query,setQuery]=useState('');
  const [tenantForm,setTenantForm]=useState<Tenant|'new'|null>(null);const [editMode,setEditMode]=useState(false);const [expiry,setExpiry]=useState('');const [saving,setSaving]=useState(false);const [admins,setAdmins]=useState<TenantAdmin[]>([]);const [adminsLoading,setAdminsLoading]=useState(false);const [adminsError,setAdminsError]=useState('');
  const load=()=>api<Tenant[]>('/hq/tenants').then(setItems);useEffect(()=>{void load()},[]);
  const filtered=items.filter(item=>item.name.toLowerCase().includes(query.trim().toLowerCase()));
  function openCreate(){setTenantForm('new');setEditMode(true);setExpiry('');setMessage('')}
  function openEdit(item:Tenant){setTenantForm(item);setEditMode(false);setExpiry(item.valid_until?new Date(item.valid_until).toISOString().slice(0,10):'');setAdmins([]);setAdminsLoading(true);setAdminsError('');setMessage('');void api<TenantAdmin[]>(`/hq/tenants/${item.id}/admins`).then(setAdmins).catch(e=>setAdminsError((e as Error).message)).finally(()=>setAdminsLoading(false))}
  function validity(item:Tenant){if(!item.valid_until)return {label:'永久有效',tone:'green'};const days=Math.ceil((new Date(item.valid_until).getTime()-Date.now())/86400000);if(days<0)return {label:'已到期',tone:'red'};if(days<=30)return {label:`${days} 天后到期`,tone:'amber'};return {label:new Date(item.valid_until).toLocaleDateString(),tone:'green'}}
  async function submitTenant(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!tenantForm)return;const editing=tenantForm==='new'?null:tenantForm;const form=new FormData(e.currentTarget);setSaving(true);try{await api(editing?`/hq/tenants/${editing.id}`:'/hq/tenants',{method:editing?'PATCH':'POST',body:JSON.stringify(editing?{name:form.get('name'),validUntil:expiry?new Date(`${expiry}T23:59:59`).toISOString():null}:{name:form.get('name'),adminName:form.get('adminName'),adminMobile:form.get('adminMobile'),adminPassword:form.get('adminPassword')})});if(editing)await Promise.all(admins.map(admin=>api(`/hq/tenants/${editing.id}/admins/${admin.id}`,{method:'PATCH',body:JSON.stringify({name:form.get(`adminName-${admin.id}`),mobile:form.get(`adminMobile-${admin.id}`),password:form.get(`adminPassword-${admin.id}`)})})));setTenantForm(null);setMessage(editing?'租户及管理员信息已更新':'租户及初始管理员账号已创建');await load();}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}
  async function toggle(item:Tenant){try{await api(`/hq/tenants/${item.id}/status`,{method:'PATCH',body:JSON.stringify({status:item.status==='active'?'suspended':'active'})});setMessage(item.status==='active'?'租户已停用':'租户已恢复');await load()}catch(e){setMessage((e as Error).message)}}
  const editing=tenantForm==='new'||tenantForm===null?null:tenantForm;
  return <><PageHeader title="租户管理" subtitle="开通客户空间、控制服务状态与查看使用规模" action={<div className="header-actions"><span className="count">{items.length} 个租户</span><button className="primary" onClick={openCreate}>+ 开通新租户</button></div>}/>{message&&<div className="notice">{message}</div>}
  <section className="card tenant-list-card">
    <div className="card-head"><h2>租户列表</h2><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索租户"/></div>
    <div className="tenant-table-scroll"><table><thead><tr><th>租户</th><th>活动数</th><th>电子票额度</th><th>服务状态</th><th>有效期</th><th>开通时间</th><th/></tr></thead>
      <tbody>{filtered.map(item=>{const valid=validity(item);const balance=item.credit_balance;const reserved=item.credit_reserved;return <tr key={item.id}>
        <td><b>{item.name}</b><small className="id">{item.id}</small></td>
        <td>{item.event_count}</td>
        <td>{balance==null||reserved==null?<span className="muted">额度数据不可用</span>:<div className="tenant-credit"><b>可用 {(balance-reserved).toLocaleString()} 张</b><small>余额 {balance.toLocaleString()} · 已预留 {reserved.toLocaleString()}</small></div>}</td>
        <td><span className={`badge ${item.status==='active'?'green':'red'}`}>{item.status==='active'?'正常':'已停用'}</span></td>
        <td><span className={`badge ${valid.tone}`}>{valid.label}</span></td>
        <td>{new Date(item.created_at).toLocaleDateString()}</td>
        <td><div className="row-actions"><button onClick={()=>openEdit(item)}>管理</button><button onClick={()=>toggle(item)}>{item.status==='active'?'停用':'恢复'}</button></div></td>
      </tr>})}</tbody>
    </table></div>
    {filtered.length===0&&<div className="table-empty">没有匹配的租户</div>}
  </section>
  {tenantForm&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setTenantForm(null)}}><section className="modal"><div className="modal-head"><div><p className="eyebrow">{editing?'TENANT PROFILE':'NEW TENANT'}</p><h2>{editing?'管理租户':'开通新租户'}</h2></div>{editing&&!editMode?<button type="button" className="primary modal-edit" onClick={()=>setEditMode(true)}>编辑</button>:<button className="close" type="button" onClick={()=>setTenantForm(null)}>×</button>}</div><form key={editing?.id??'new'} onSubmit={submitTenant}><label>租户名称<input name="name" required minLength={2} readOnly={Boolean(editing&&!editMode)} defaultValue={editing?.name??''} placeholder="输入企业或组织完整名称"/></label>{!editing&&<><div className="form-section"><b>初始租户管理员</b><small>该手机号用于登录活动管理平台，开通后请安全交付给租户。</small></div><label>管理员姓名<input name="adminName" required minLength={2} maxLength={50} placeholder="例如：张三"/></label><label>管理员手机号<input name="adminMobile" type="tel" required pattern="1[3-9][0-9]{9}" autoComplete="tel" placeholder="请输入 11 位手机号"/></label><label>初始密码<input name="adminPassword" type="password" required minLength={8} maxLength={128} autoComplete="new-password" placeholder="至少 8 位"/></label></>}{editing&&<><label>服务有效期<input type="date" disabled={!editMode} value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><div className="tenant-admin-list"><div className="tenant-admin-head"><div><b>租户管理员</b></div></div>{adminsLoading?<small className="admin-loading">正在加载租户管理员…</small>:adminsError?<small className="admin-error">加载失败：{adminsError}</small>:admins.length>0?admins.map(admin=>editMode?<div className="tenant-admin-fields" key={admin.id}><label>姓名<input name={`adminName-${admin.id}`} required minLength={2} maxLength={50} defaultValue={admin.name}/></label><label>手机号<input name={`adminMobile-${admin.id}`} type="tel" required pattern="1[3-9][0-9]{9}" defaultValue={admin.mobile??''} placeholder="请输入 11 位手机号"/></label><label>新密码（选填）<input name={`adminPassword-${admin.id}`} type="password" minLength={8} maxLength={128} autoComplete="new-password" placeholder="留空则不修改密码"/></label></div>:<div className="tenant-admin-row" key={admin.id}><div><b>{admin.name}</b><small>{admin.mobile??admin.username??'未设置手机号'}</small></div></div>):<small className="admin-loading">该租户暂未设置管理员。</small>}</div><div className="tenant-summary"><span>租户 ID</span><code>{editing.id}</code><span>活动收款</span><b>暂未接入</b><span>当前状态</span><b>{editing.status==='active'?'正常服务':'已停用'}</b></div></>}<div className="modal-actions"><button type="button" onClick={()=>setTenantForm(null)}>{editMode?'取消':'关闭'}</button>{(!editing||editMode)&&<button className="primary" disabled={saving}>{saving?'保存中…':editing?'保存修改':'立即开通'}</button>}</div></form></section></div>}</>}

function TenantPicker({tenants,value,onChange}:{tenants:Tenant[];value:string;onChange:(tenantId:string)=>void}){
  const[open,setOpen]=useState(false);const[query,setQuery]=useState('');const[activeIndex,setActiveIndex]=useState(0);
  const rootRef=useRef<HTMLDivElement>(null);const inputRef=useRef<HTMLInputElement>(null);
  const selected=tenants.find(tenant=>tenant.id===value);
  const keyword=query.trim().toLowerCase();
  const matches=tenants.filter(tenant=>tenant.name.toLowerCase().includes(keyword)||tenant.id.toLowerCase().includes(keyword));
  useEffect(()=>{if(!open)return;function closeOnOutsideClick(e:PointerEvent){if(!rootRef.current?.contains(e.target as Node))setOpen(false)}document.addEventListener('pointerdown',closeOnOutsideClick);return()=>document.removeEventListener('pointerdown',closeOnOutsideClick)},[open]);
  function choose(tenant:Tenant){onChange(tenant.id);setOpen(false);setQuery('');inputRef.current?.blur()}
  return <div className="tenant-picker" ref={rootRef} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))setOpen(false)}}>
    <label htmlFor="credit-tenant-search">选择租户</label>
    <div className="tenant-picker-field"><input id="credit-tenant-search" ref={inputRef} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls="credit-tenant-options" aria-activedescendant={open&&matches[activeIndex]?`credit-tenant-${matches[activeIndex].id}`:undefined} value={open?query:selected?.name??''} placeholder="输入租户名称或编号筛选" disabled={tenants.length===0} onFocus={()=>{setQuery('');setActiveIndex(0);setOpen(true)}} onChange={e=>{setQuery(e.target.value);setActiveIndex(0);setOpen(true)}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();if(!open){setOpen(true);return}setActiveIndex(index=>Math.min(index+1,Math.max(matches.length-1,0)))}else if(e.key==='ArrowUp'){e.preventDefault();setActiveIndex(index=>Math.max(index-1,0))}else if(e.key==='Enter'&&open&&matches[activeIndex]){e.preventDefault();choose(matches[activeIndex])}else if(e.key==='Escape'){setOpen(false);inputRef.current?.blur()}}}/><svg className="tenant-picker-chevron" aria-hidden="true" viewBox="0 0 20 20" fill="none"><path d="m5 7.5 5 5 5-5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg></div>
    {open&&<div id="credit-tenant-options" className="tenant-picker-options" role="listbox">{matches.length?matches.map((tenant,index)=><button id={`credit-tenant-${tenant.id}`} key={tenant.id} type="button" role="option" aria-selected={tenant.id===value} className={index===activeIndex?'active':''} onMouseEnter={()=>setActiveIndex(index)} onClick={()=>choose(tenant)}><b>{tenant.name}</b><small>{tenant.id}</small></button>):<div className="tenant-picker-empty">没有匹配的租户</div>}</div>}
  </div>
}

function Credits({user}:{user:User}){
  const[tenants,setTenants]=useState<Tenant[]>([]);const[tenantId,setTenantId]=useState('');const[wallet,setWallet]=useState<CreditWallet>();const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
  const grantAttempt=useRef<{signature:string;reference:string}|null>(null);
  useEffect(()=>{void api<Tenant[]>('/hq/tenants').then(items=>{setTenants(items);setTenantId(items[0]?.id??'')}).catch(e=>setError((e as Error).message))},[]);
  useEffect(()=>{if(!tenantId){setWallet(undefined);return}let cancelled=false;setWallet(undefined);setError('');void api<CreditWallet>(`/hq/tenants/${tenantId}/credits`).then(result=>{if(!cancelled)setWallet(result)}).catch(e=>{if(!cancelled)setError((e as Error).message)});return()=>{cancelled=true}},[tenantId]);
  async function grant(e:FormEvent<HTMLFormElement>){e.preventDefault();const element=e.currentTarget;const form=new FormData(element);const payload={amount:Number(form.get('amount')),reason:String(form.get('reason'))};const signature=JSON.stringify({tenantId,...payload});if(grantAttempt.current?.signature!==signature)grantAttempt.current={signature,reference:crypto.randomUUID()};setBusy(true);setError('');setNotice('');try{await api(`/hq/tenants/${tenantId}/credits`,{method:'POST',body:JSON.stringify({...payload,reference:grantAttempt.current.reference})});grantAttempt.current=null;setWallet(await api<CreditWallet>(`/hq/tenants/${tenantId}/credits`));element.reset();setNotice('额度已发放并记录审计流水')}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  return <><PageHeader title="电子票额度" subtitle="赠送与购买统一余额；人工补发必须留痕"/>{error&&<div className="alert">{error}</div>}{notice&&<div className="notice">{notice}</div>}<section className="card"><TenantPicker tenants={tenants} value={tenantId} onChange={setTenantId}/>{wallet&&<><section className="metrics"><Metric label="可用额度" value={String(wallet.available)} note="可供新报名预留"/><Metric label="已预留" value={String(wallet.reserved)} note="待支付订单"/><Metric label="账户余额" value={String(wallet.balance)} note="不区分赠送与购买"/></section>{(user.role==='super_admin'||user.role==='finance')&&<form onSubmit={grant}><h2>人工补发额度</h2><p className="muted">仅用于已核实的线下购买或运营补发，不代表在线付款成功。</p><label>增加张数<input name="amount" type="number" min="1" max="1000000" required/></label><label>补发原因<input name="reason" minLength={4} maxLength={200} required placeholder="填写订单号或审批依据"/></label><button className="primary" disabled={busy}>{busy?'处理中…':'确认补发'}</button></form>}<h2>最近流水</h2><table><thead><tr><th>时间</th><th>类型</th><th>张数</th><th>说明</th></tr></thead><tbody>{wallet.entries.map(entry=><tr key={entry.id}><td>{new Date(entry.created_at).toLocaleString()}</td><td>{({grant:'注册赠送',purchase:'购买',manual:'人工补发',issue:'出票消耗',return:'票券返还',refund:'退款冲减'} as Record<string,string>)[entry.kind]??entry.kind}</td><td>{entry.change>0?'+':''}{entry.change}</td><td>{entry.note}</td></tr>)}</tbody></table></>}</section></>;
}

function Channels(){return <><PageHeader title="支付渠道" subtitle="统一管理收款能力、回调状态与对账配置" action={<button className="primary">新增渠道</button>}/><section className="card"><div className="channel"><div className="channel-logo alipay">支</div><div><h3>支付宝</h3><p>网页与移动端支付</p></div><span className="badge">未启用</span><button>配置</button></div></section></>}
function Risk(){return <><PageHeader title="风控中心" subtitle="监测登录、交易、报名与验签异常"/><section className="metrics"><Metric label="高风险事件" value="0" note="过去 24 小时"/><Metric label="登录失败" value="0" note="过去 24 小时"/><Metric label="重复验签" value="1" note="联调测试数据"/><Metric label="退款异常" value="0" note="待接支付渠道"/></section><section className="card empty-state"><b>✓</b><h2>当前没有待处理风险</h2><p>系统将持续检查异常登录、库存竞争、支付回调和重复验签。</p></section></>}
function AuditLogs(){const[logs,setLogs]=useState<Audit[]>([]);useEffect(()=>{void api<Audit[]>('/hq/audit-logs').then(setLogs)},[]);return <><PageHeader title="审计日志" subtitle="总部敏感操作的不可抵赖记录"/><section className="card"><table><thead><tr><th>时间</th><th>操作人</th><th>动作</th><th>对象</th><th>来源 IP</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td>{new Date(log.created_at).toLocaleString()}</td><td>{log.display_name}</td><td><code>{log.action}</code></td><td>{log.target_type}{log.target_id?` · ${log.target_id.slice(0,8)}`:''}</td><td>{log.ip_address??'-'}</td></tr>)}</tbody></table></section></>}
function Settings(){return <><PageHeader title="平台设置" subtitle="配置品牌、安全策略和系统级参数"/><div className="settings-grid"><section className="card"><h2>品牌信息</h2><label>平台名称<input defaultValue="EventVivid"/></label><label>总部后台名称<input defaultValue="总部运营中心"/></label><button className="primary">保存品牌设置</button></section><section className="card"><h2>安全策略</h2><label className="switch-row"><span>总部管理员登录审计<small>记录登录时间与来源 IP</small></span><input type="checkbox" defaultChecked/></label><label className="switch-row"><span>敏感操作二次确认<small>停用租户、修改支付渠道时触发</small></span><input type="checkbox" defaultChecked/></label></section></div></>}

export function App(){const[user,setUser]=useState<User|null>(null);const[checking,setChecking]=useState(Boolean(session.get()));const navigate=useNavigate();useEffect(()=>{if(!session.get()){setChecking(false);return}void api<User>('/hq/auth/me').then(setUser).catch(()=>session.clear()).finally(()=>setChecking(false))},[]);function logout(){session.clear();setUser(null);navigate('/')}if(checking)return <Loading/>;if(!user)return <Login onLogin={setUser}/>;return <Layout user={user} onLogout={logout}><Routes><Route path="/" element={<Dashboard/>}/><Route path="/tenants" element={<Tenants/>}/><Route path="/credits" element={<Credits user={user}/>}/><Route path="/channels" element={<Channels/>}/><Route path="/risk" element={<Risk/>}/><Route path="/audit" element={<AuditLogs/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></Layout>}
